carregar_scripts_pattern_causality <- function() {
  
source(here("CASUALIDADE/pattern_causality/R/","classes.r"))
source(here("CASUALIDADE/pattern_causality/R/","convertSignatureToValue.r"))
source(here("CASUALIDADE/pattern_causality/R/","data.r"))
source(here("CASUALIDADE/pattern_causality/R/","dataBank.r"))
source(here("CASUALIDADE/pattern_causality/R/","distanceMatrix.r"))
source(here("CASUALIDADE/pattern_causality/R/","fillPCMatrix.r"))
source(here("CASUALIDADE/pattern_causality/R/","firstCausalityPoint.r"))
source(here("CASUALIDADE/pattern_causality/R/","firstCausalityPointCHECK.r"))
source(here("CASUALIDADE/pattern_causality/R/","geom-rtile.r"))
source(here("CASUALIDADE/pattern_causality/R/","interfaces.r"))
source(here("CASUALIDADE/pattern_causality/R/","natureOfCausality.r"))
source(here("CASUALIDADE/pattern_causality/R/","optimalParametersSearch.r"))
source(here("CASUALIDADE/pattern_causality/R/","pastNNsInfo.r"))
source(here("CASUALIDADE/pattern_causality/R/","patternHashing.r"))
source(here("CASUALIDADE/pattern_causality/R/","patternSpace.r"))
source(here("CASUALIDADE/pattern_causality/R/","pattern_utils.r"))
source(here("CASUALIDADE/pattern_causality/R/","PC.Mk.II.Full.Details.r"))
source(here("CASUALIDADE/pattern_causality/R/","PC.Mk.II.Lightweight.r"))
source(here("CASUALIDADE/pattern_causality/R/","pcAccuracy.r"))
source(here("CASUALIDADE/pattern_causality/R/","pcCrossMatrix.r"))
source(here("CASUALIDADE/pattern_causality/R/","pcCV.r"))
source(here("CASUALIDADE/pattern_causality/R/","pcEffect.r"))
source(here("CASUALIDADE/pattern_causality/R/","pcMatrix.r"))
source(here("CASUALIDADE/pattern_causality/R/","pc_accuracy_methods.r"))
source(here("CASUALIDADE/pattern_causality/R/","pc_check.r"))
source(here("CASUALIDADE/pattern_causality/R/","pc_full_details_utils.r"))
source(here("CASUALIDADE/pattern_causality/R/","pc_lightweight_utils.r"))
source(here("CASUALIDADE/pattern_causality/R/","pc_nature.r"))
source(here("CASUALIDADE/pattern_causality/R/","pc_neighbors.r"))
source(here("CASUALIDADE/pattern_causality/R/","pc_params.r"))
source(here("CASUALIDADE/pattern_causality/R/","pc_point.r"))
source(here("CASUALIDADE/pattern_causality/R/","pc_strength.r"))
source(here("CASUALIDADE/pattern_causality/R/","predictionY.r"))
source(here("CASUALIDADE/pattern_causality/R/","projectedNNsInfo.r"))
source(here("CASUALIDADE/pattern_causality/R/","signatureSpace.r"))
source(here("CASUALIDADE/pattern_causality/R/","stateSpace.r"))

  print("Todos os scripts foram carregados com sucesso!") # Mensagem opcional
}
