library(dplyr)
library(tidyr)
library(readxl)

#data <- read_excel("Excel/Combatendo as Mudanças Climáticas.xlsx")

data <- Grupo1
data <- data[-1, ]

data <- data[c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,31,32,33,34,76,77,78,79,80,81,82,83,84,85)]

data <- data %>%
  mutate (
    
    Gender_male = ifelse(`Qual é o seu gênero?` == 'Homem', 1, 0),                                                                                                              
    Gender_female = ifelse(`Qual é o seu gênero?` == 'Mulher', 1, 0),                                                                                                             
    Gender_Other = ifelse(`Qual é o seu gênero?` == 'Outro', 1, 0),  
    
    Age_18_24_No = ifelse(`Eu tenho entre 18 e 24 anos` == 'Não', 1, 0),                                                                                                         
    Age_18_24_yes = ifelse(`Eu tenho entre 18 e 24 anos` == 'Sim', 1, 0),
    
    employment_employee = ifelse(`Qual é a sua situação empregatícia?` == 'Empregado(a)', 1, 0),                                                                                        
    employment_studant = ifelse(`Qual é a sua situação empregatícia?` == 'Estudando ou em treinamento', 1, 0),                                                                         
    employment_no_employee = ifelse(`Qual é a sua situação empregatícia?` == 'Não estou empregado(a), nem estudando ou em treinamento', 1, 0),
    
    primary_education     = ifelse(`Qual é o nível de escolaridade da sua mãe?` == 'Ensino Fundamental', 1, 0),
    High_school           = ifelse(`Qual é o nível de escolaridade da sua mãe?` == 'Ensino Médio Completo', 1, 0),                                                                        
    High_school_incomplet = ifelse(`Qual é o nível de escolaridade da sua mãe?` == 'Ensino Médio Incompleto', 1, 0),                                                                      
    higher_education      = ifelse(`Qual é o nível de escolaridade da sua mãe?` == 'Ensino Superior Completo', 1, 0),                                                                     
    higher_education_incomplet    = ifelse(`Qual é o nível de escolaridade da sua mãe?` == 'Ensino Superior Incompleto', 1, 0),                                                                   
    other_Education       = ifelse(`Qual é o nível de escolaridade da sua mãe?` == 'Nenhuma das anteriores', 1, 0),                                                                       
    Postgraduate          = ifelse(`Qual é o nível de escolaridade da sua mãe?` == 'Pós-graduação Completa', 1, 0),  
    
    Residence_Rural = ifelse(`Qual é a sua área de residência?` == 'Rural', 1, 0),                                                                                                  
    Residence_Urban = ifelse(`Qual é a sua área de residência?` == 'Urbana', 1, 0),  
    
    Race_Yellow = ifelse(`Qual é a sua raça/etnia?` == 'Amarelo', 1, 0),                                                                                                        
    Race_White = ifelse(`Qual é a sua raça/etnia?` == 'Branco', 1, 0),                                                                                                         
    Race_Indigenous = ifelse(`Qual é a sua raça/etnia?` == 'Indígena', 1, 0),                                                                                                       
    Race_Brown = ifelse(`Qual é a sua raça/etnia?` == 'Pardo', 1, 0),                                                                                                          
    Race_Black = ifelse(`Qual é a sua raça/etnia?` == 'Preto', 1, 0)
    
  )

#Comun question to all Groups
data <- data %>%
  mutate(
      VF1_1 = ifelse(`Você já fez trabalho voluntário para uma organização ambiental?` == 'Não', 1, 0),                                                                     
      VF1_2 = ifelse(`Você já fez trabalho voluntário para uma organização ambiental?` == 'Sim', 1, 0), 
      
      VF2_1 = ifelse(`Você já se envolveu em ativismo ambiental? (Por exemplo, Todos Pela Amazônia, se recusa a comprar produtos específicos, protestos, etc.)` == 'Não', 1, 0),
      VF2_2 = ifelse(`Você já se envolveu em ativismo ambiental? (Por exemplo, Todos Pela Amazônia, se recusa a comprar produtos específicos, protestos, etc.)` == 'Sim', 1, 0),
    
      VF3_1 = ifelse(`Como você se locomove no dia a dia? (por exemplo, para ir à escola/faculdade/trabalho, ir ao supermercado, visitar amigos)` == 'Na maioria das vezes, ando a pé ou de bicicleta', 1, 0),
      VF3_2 = ifelse(`Como você se locomove no dia a dia? (por exemplo, para ir à escola/faculdade/trabalho, ir ao supermercado, visitar amigos)` == 'Na maioria das vezes, pego carona ou dirijo sozinho', 1, 0),
      VF3_3 = ifelse(`Como você se locomove no dia a dia? (por exemplo, para ir à escola/faculdade/trabalho, ir ao supermercado, visitar amigos)` == 'Na maioria das vezes, uso o transporte público', 1, 0),
    
      VF4_1 = ifelse(`Qual das opções a seguir melhor descreve como você compra coisas novas (por exemplo, roupas)?` == 'Compro (ou outra pessoa compra para mim) algumas de minhas coisas novas, mas às vezes compro de segunda mão ou reutilizo coisas antigas', 1, 0),
      VF4_2 = ifelse(`Qual das opções a seguir melhor descreve como você compra coisas novas (por exemplo, roupas)?` == 'Eu compro (ou outra pessoa compra para mim) a maioria ou todas as minhas coisas novas', 1, 0),
      VF4_3 = ifelse(`Qual das opções a seguir melhor descreve como você compra coisas novas (por exemplo, roupas)?` == 'Eu compro (ou outra pessoa compra para mim) coisas novas muito raramente', 1, 0),
    
      VF5_1 = ifelse(`Você come carne (ou seja, bovina, suína ou de frango)?` == 'Não', 1, 0),
      VF5_2 = ifelse(`Você come carne (ou seja, bovina, suína ou de frango)?` == 'Sim', 1, 0),
    
      VF6_1 = ifelse(`Você come peixe?` == 'Não', 1, 0),
      VF6_2 = ifelse(`Você come peixe?` == 'Sim', 1, 0),
    
      VF7_1 = ifelse(`Você come ovos ou laticínios (por exemplo, leite, queijo, iogurte)?` == 'Não', 1, 0),
      VF7_2 = ifelse(`Você come ovos ou laticínios (por exemplo, leite, queijo, iogurte)?` == 'Sim', 1, 0),
      
      VF8_1 = ifelse(`Sua família/domicílio usa uma lixeira separada para reciclagem? Se você mora em mais de uma residência, pense em onde você passa a maior parte do tempo.` == 'Não', 1, 0),                                                                                                                                                 
      VF8_2 = ifelse(`Sua família/domicílio usa uma lixeira separada para reciclagem? Se você mora em mais de uma residência, pense em onde você passa a maior parte do tempo.` == 'Não sei', 1, 0),                                                                                                                                             
      VF8_3 = ifelse(`Sua família/domicílio usa uma lixeira separada para reciclagem? Se você mora em mais de uma residência, pense em onde você passa a maior parte do tempo.` == 'Sim', 1, 0),                                                                                                                                                 
      
      VF9_1 = ifelse(`Sua família/domicílio usa uma lixeira separada para resíduos de alimentos (por exemplo, sobras, cascas de frutas, cascas de ovos)? Se você mora em mais de uma residência, pense em onde você passa a maior parte do tempo.` == 'Não sei', 1, 0),                                                                          
      VF9_2 = ifelse(`Sua família/domicílio usa uma lixeira separada para resíduos de alimentos (por exemplo, sobras, cascas de frutas, cascas de ovos)? Se você mora em mais de uma residência, pense em onde você passa a maior parte do tempo.` == 'Não, os resíduos de alimentos são colocados junto com o lixo geral', 1, 0),               
      VF9_3 = ifelse(`Sua família/domicílio usa uma lixeira separada para resíduos de alimentos (por exemplo, sobras, cascas de frutas, cascas de ovos)? Se você mora em mais de uma residência, pense em onde você passa a maior parte do tempo.` == 'Sim, há uma lixeira separada para resíduos de alimentos ou uma lixeira de compostagem', 1, 0),
      
      VF10_1 = ifelse(`Gostaríamos de saber qual você acha que é o motivo mais importante para proteger a natureza. Por favor, escolha um motivo da lista a seguir:` == 'Não acho que seja importante proteger a natureza', 1, 0),                                                                                                                
      VF10_2 = ifelse(`Gostaríamos de saber qual você acha que é o motivo mais importante para proteger a natureza. Por favor, escolha um motivo da lista a seguir:` == 'Outro motivo', 1, 0),                                                                                                                                                    
      VF10_3 = ifelse(`Gostaríamos de saber qual você acha que é o motivo mais importante para proteger a natureza. Por favor, escolha um motivo da lista a seguir:` == 'Para evitar desastres naturais (por exemplo, enchentes)', 1, 0),                                                                                                         
      VF10_4 = ifelse(`Gostaríamos de saber qual você acha que é o motivo mais importante para proteger a natureza. Por favor, escolha um motivo da lista a seguir:` == 'Para o bem das gerações futuras', 1, 0),                                                                                                                                 
      VF10_5 = ifelse(`Gostaríamos de saber qual você acha que é o motivo mais importante para proteger a natureza. Por favor, escolha um motivo da lista a seguir:` == 'Para proteger animais e plantas (não humanos) (por exemplo, impedir a extinção de animais)', 1, 0),                                                                      
      VF10_6 = ifelse(`Gostaríamos de saber qual você acha que é o motivo mais importante para proteger a natureza. Por favor, escolha um motivo da lista a seguir:` == 'Para que possamos continuar a desfrutar da beleza da natureza', 1, 0),                                                                                                   
      VF10_7 = ifelse(`Gostaríamos de saber qual você acha que é o motivo mais importante para proteger a natureza. Por favor, escolha um motivo da lista a seguir:` == 'Para ter uma área local limpa (por exemplo, ter ar e rios limpos)', 1, 0)

  )

#Grupo1
data <- data %>%
  mutate (
    MudancaClimatica1 = case_when (
      `A mudança climática é causada pelas decisões e comportamentos das pessoas no passado e no presente. Cientistas concordam há mais de 30 anos que a mudança climática está acontecendo, mas as gerações mais velhas não fizeram o suficiente para impedi-la. Agora, os efeitos das mudanças climáticas já estão sendo vistos em todo o mundo e provavelmente serão piores no futuro.Isso significa que, quanto mais jovem você for agora, mais você irá experimentar os efeitos das mudanças climáticas. As gerações futuras provavelmente enfrentarão os piores efeitos, incluindo eventos climáticos extremos, como tempestades, secas e inundações.Jovens de todo o mundo começaram a criticar as pessoas mais velhas e os governos por não levarem a mudança climática a sério o suficiente. Eles estão exigindo que os tomadores de decisão comecem a agir de verdade com urgência.Nesta seção, estamos interessados em saber seus pensamentos e opiniões como um jovem nos dias de hoje.Como uma pessoa jovem, quão importante você acha que é proteger o meio ambiente?` == '1 (Nada importante)' ~ 1,       
      `A mudança climática é causada pelas decisões e comportamentos das pessoas no passado e no presente. Cientistas concordam há mais de 30 anos que a mudança climática está acontecendo, mas as gerações mais velhas não fizeram o suficiente para impedi-la. Agora, os efeitos das mudanças climáticas já estão sendo vistos em todo o mundo e provavelmente serão piores no futuro.Isso significa que, quanto mais jovem você for agora, mais você irá experimentar os efeitos das mudanças climáticas. As gerações futuras provavelmente enfrentarão os piores efeitos, incluindo eventos climáticos extremos, como tempestades, secas e inundações.Jovens de todo o mundo começaram a criticar as pessoas mais velhas e os governos por não levarem a mudança climática a sério o suficiente. Eles estão exigindo que os tomadores de decisão comecem a agir de verdade com urgência.Nesta seção, estamos interessados em saber seus pensamentos e opiniões como um jovem nos dias de hoje.Como uma pessoa jovem, quão importante você acha que é proteger o meio ambiente?` == '4' ~ 4,                         
      `A mudança climática é causada pelas decisões e comportamentos das pessoas no passado e no presente. Cientistas concordam há mais de 30 anos que a mudança climática está acontecendo, mas as gerações mais velhas não fizeram o suficiente para impedi-la. Agora, os efeitos das mudanças climáticas já estão sendo vistos em todo o mundo e provavelmente serão piores no futuro.Isso significa que, quanto mais jovem você for agora, mais você irá experimentar os efeitos das mudanças climáticas. As gerações futuras provavelmente enfrentarão os piores efeitos, incluindo eventos climáticos extremos, como tempestades, secas e inundações.Jovens de todo o mundo começaram a criticar as pessoas mais velhas e os governos por não levarem a mudança climática a sério o suficiente. Eles estão exigindo que os tomadores de decisão comecem a agir de verdade com urgência.Nesta seção, estamos interessados em saber seus pensamentos e opiniões como um jovem nos dias de hoje.Como uma pessoa jovem, quão importante você acha que é proteger o meio ambiente?` == '5' ~ 5,                         
      `A mudança climática é causada pelas decisões e comportamentos das pessoas no passado e no presente. Cientistas concordam há mais de 30 anos que a mudança climática está acontecendo, mas as gerações mais velhas não fizeram o suficiente para impedi-la. Agora, os efeitos das mudanças climáticas já estão sendo vistos em todo o mundo e provavelmente serão piores no futuro.Isso significa que, quanto mais jovem você for agora, mais você irá experimentar os efeitos das mudanças climáticas. As gerações futuras provavelmente enfrentarão os piores efeitos, incluindo eventos climáticos extremos, como tempestades, secas e inundações.Jovens de todo o mundo começaram a criticar as pessoas mais velhas e os governos por não levarem a mudança climática a sério o suficiente. Eles estão exigindo que os tomadores de decisão comecem a agir de verdade com urgência.Nesta seção, estamos interessados em saber seus pensamentos e opiniões como um jovem nos dias de hoje.Como uma pessoa jovem, quão importante você acha que é proteger o meio ambiente?` == '6' ~ 6,                         
      `A mudança climática é causada pelas decisões e comportamentos das pessoas no passado e no presente. Cientistas concordam há mais de 30 anos que a mudança climática está acontecendo, mas as gerações mais velhas não fizeram o suficiente para impedi-la. Agora, os efeitos das mudanças climáticas já estão sendo vistos em todo o mundo e provavelmente serão piores no futuro.Isso significa que, quanto mais jovem você for agora, mais você irá experimentar os efeitos das mudanças climáticas. As gerações futuras provavelmente enfrentarão os piores efeitos, incluindo eventos climáticos extremos, como tempestades, secas e inundações.Jovens de todo o mundo começaram a criticar as pessoas mais velhas e os governos por não levarem a mudança climática a sério o suficiente. Eles estão exigindo que os tomadores de decisão comecem a agir de verdade com urgência.Nesta seção, estamos interessados em saber seus pensamentos e opiniões como um jovem nos dias de hoje.Como uma pessoa jovem, quão importante você acha que é proteger o meio ambiente?` == '7 (Extremamente importante)' ~ 7
    ),
    MudancaClimatica2 =  case_when (
      `Como uma pessoa jovem, de modo geral, quão preocupado(a) você está com as mudanças climáticas?` == '1 (Nada preocupado)' ~ 1,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
      `Como uma pessoa jovem, de modo geral, quão preocupado(a) você está com as mudanças climáticas?` == '2' ~ 2,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
      `Como uma pessoa jovem, de modo geral, quão preocupado(a) você está com as mudanças climáticas?` == '3' ~ 3,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
      `Como uma pessoa jovem, de modo geral, quão preocupado(a) você está com as mudanças climáticas?` == '4' ~ 4,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
      `Como uma pessoa jovem, de modo geral, quão preocupado(a) você está com as mudanças climáticas?` == '5' ~ 5,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
      `Como uma pessoa jovem, de modo geral, quão preocupado(a) você está com as mudanças climáticas?` == '6' ~ 6,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
      `Como uma pessoa jovem, de modo geral, quão preocupado(a) você está com as mudanças climáticas?` == '7 (Extremamente preocupado)' ~ 7
    ),
    MudancaClimatica3 =  case_when (	
      `Quão preocupadas você acha que estão as pessoas no Brasil com 40 anos ou mais em relação às mudanças climáticas?` == '1 (Nada preocupadas)' ~ 1,                                                                                                                                                                                                                              
      `Quão preocupadas você acha que estão as pessoas no Brasil com 40 anos ou mais em relação às mudanças climáticas?` == '2' ~ 2,                                                                                                                                                                                                                                                 
      `Quão preocupadas você acha que estão as pessoas no Brasil com 40 anos ou mais em relação às mudanças climáticas?` == '3' ~ 3,                                                                                                                                                                                                                                                 
      `Quão preocupadas você acha que estão as pessoas no Brasil com 40 anos ou mais em relação às mudanças climáticas?` == '4' ~ 4,                                                                                                                                                                                                                                                 
      `Quão preocupadas você acha que estão as pessoas no Brasil com 40 anos ou mais em relação às mudanças climáticas?` == '5' ~ 5,                                                                                                                                                                                                                                                 
      `Quão preocupadas você acha que estão as pessoas no Brasil com 40 anos ou mais em relação às mudanças climáticas?` == '6' ~ 6,                                                                                                                                                                                                                                                 
      `Quão preocupadas você acha que estão as pessoas no Brasil com 40 anos ou mais em relação às mudanças climáticas?` == '7 (Extremamente preocupadas)' ~ 7, 
    ),
    MudancaClimatica4 =  case_when (																																																							 
      `Também gostaríamos de saber o que você acha que seus colegas (ou seja, outros jovens) pensam sobre as mudanças climáticas.O quanto você acha que outros jovens em geral no Brasil estão preocupados com as mudanças climáticas?` == '1 (Nada preocupados)' ~ 1,                                                                                                               
      `Também gostaríamos de saber o que você acha que seus colegas (ou seja, outros jovens) pensam sobre as mudanças climáticas.O quanto você acha que outros jovens em geral no Brasil estão preocupados com as mudanças climáticas?` == '2' ~ 2,                                                                                                                                  
      `Também gostaríamos de saber o que você acha que seus colegas (ou seja, outros jovens) pensam sobre as mudanças climáticas.O quanto você acha que outros jovens em geral no Brasil estão preocupados com as mudanças climáticas?` == '3' ~ 3,                                                                                                                                  
      `Também gostaríamos de saber o que você acha que seus colegas (ou seja, outros jovens) pensam sobre as mudanças climáticas.O quanto você acha que outros jovens em geral no Brasil estão preocupados com as mudanças climáticas?` == '4' ~ 4,                                                                                                                                  
      `Também gostaríamos de saber o que você acha que seus colegas (ou seja, outros jovens) pensam sobre as mudanças climáticas.O quanto você acha que outros jovens em geral no Brasil estão preocupados com as mudanças climáticas?` == '5' ~ 5,                                                                                                                                  
      `Também gostaríamos de saber o que você acha que seus colegas (ou seja, outros jovens) pensam sobre as mudanças climáticas.O quanto você acha que outros jovens em geral no Brasil estão preocupados com as mudanças climáticas?` == '6' ~ 6,                                                                                                                                  
      `Também gostaríamos de saber o que você acha que seus colegas (ou seja, outros jovens) pensam sobre as mudanças climáticas.O quanto você acha que outros jovens em geral no Brasil estão preocupados com as mudanças climáticas?` == '7 (Extremamente preocupados)' ~ 7,                                                                                                       
    ),
    MudancaClimatica5 =  case_when (	
      `Quão preocupados você acha que estão seus amigos próximos em relação às mudanças climáticas?` == '1 (Nada preocupados)' ~ 1,                                                                                                                                                                                                                                                  
      `Quão preocupados você acha que estão seus amigos próximos em relação às mudanças climáticas?` == '2' ~ 2,                                                                                                                                                                                                                                                                     
      `Quão preocupados você acha que estão seus amigos próximos em relação às mudanças climáticas?` == '3' ~ 3,                                                                                                                                                                                                                                                                     
      `Quão preocupados você acha que estão seus amigos próximos em relação às mudanças climáticas?` == '4' ~ 4,                                                                                                                                                                                                                                                                     
      `Quão preocupados você acha que estão seus amigos próximos em relação às mudanças climáticas?` == '5' ~ 5,                                                                                                                                                                                                                                                                     
      `Quão preocupados você acha que estão seus amigos próximos em relação às mudanças climáticas?` == '6' ~ 6,                                                                                                                                                                                                                                                                     
      `Quão preocupados você acha que estão seus amigos próximos em relação às mudanças climáticas?` == '7 (Extremamente preocupados)' ~ 7,                                                                                                                                                                                                                                          
    ),
    MudancaClimatica6 =  case_when (	
      `Um estudo mostrou que a maioria dos brasileiros (64%) com mais de 60 anos não acredita que cientistas e ambientalistas exageram ao tratar da crise do clima, isto é, pessoas mais velhas acreditam nos alertas de cientistas, demonstrando preocupação em relação às mudanças climáticas.Quão surpreso(a) você está com esses resultados?` == '1 (Nada surpreso)' ~ 1,        
      `Um estudo mostrou que a maioria dos brasileiros (64%) com mais de 60 anos não acredita que cientistas e ambientalistas exageram ao tratar da crise do clima, isto é, pessoas mais velhas acreditam nos alertas de cientistas, demonstrando preocupação em relação às mudanças climáticas.Quão surpreso(a) você está com esses resultados?` == '2' ~ 2,                        
      `Um estudo mostrou que a maioria dos brasileiros (64%) com mais de 60 anos não acredita que cientistas e ambientalistas exageram ao tratar da crise do clima, isto é, pessoas mais velhas acreditam nos alertas de cientistas, demonstrando preocupação em relação às mudanças climáticas.Quão surpreso(a) você está com esses resultados?` == '3' ~ 3,                        
      `Um estudo mostrou que a maioria dos brasileiros (64%) com mais de 60 anos não acredita que cientistas e ambientalistas exageram ao tratar da crise do clima, isto é, pessoas mais velhas acreditam nos alertas de cientistas, demonstrando preocupação em relação às mudanças climáticas.Quão surpreso(a) você está com esses resultados?` == '4' ~ 4,                        
      `Um estudo mostrou que a maioria dos brasileiros (64%) com mais de 60 anos não acredita que cientistas e ambientalistas exageram ao tratar da crise do clima, isto é, pessoas mais velhas acreditam nos alertas de cientistas, demonstrando preocupação em relação às mudanças climáticas.Quão surpreso(a) você está com esses resultados?` == '5' ~ 5,                        
      `Um estudo mostrou que a maioria dos brasileiros (64%) com mais de 60 anos não acredita que cientistas e ambientalistas exageram ao tratar da crise do clima, isto é, pessoas mais velhas acreditam nos alertas de cientistas, demonstrando preocupação em relação às mudanças climáticas.Quão surpreso(a) você está com esses resultados?` == '6' ~ 6,                        
      `Um estudo mostrou que a maioria dos brasileiros (64%) com mais de 60 anos não acredita que cientistas e ambientalistas exageram ao tratar da crise do clima, isto é, pessoas mais velhas acreditam nos alertas de cientistas, demonstrando preocupação em relação às mudanças climáticas.Quão surpreso(a) você está com esses resultados?` == '7 (Extremamente surpreso)' ~ 7,
    ),
    MudancaClimatica7 =  case_when (	
      `É provável que a maioria das pessoas no Brasil faça sua parte no esforço conjunto para combater as mudanças climáticas` == '1 (Discordo completamente)' ~ 1,                                                                                                                                                                                                                  
      `É provável que a maioria das pessoas no Brasil faça sua parte no esforço conjunto para combater as mudanças climáticas` == '2' ~ 2,                                                                                                                                                                                                                                           
      `É provável que a maioria das pessoas no Brasil faça sua parte no esforço conjunto para combater as mudanças climáticas` == '3' ~ 3,                                                                                                                                                                                                                                           
      `É provável que a maioria das pessoas no Brasil faça sua parte no esforço conjunto para combater as mudanças climáticas` == '4' ~ 4,                                                                                                                                                                                                                                           
      `É provável que a maioria das pessoas no Brasil faça sua parte no esforço conjunto para combater as mudanças climáticas` == '5' ~ 5,                                                                                                                                                                                                                                           
      `É provável que a maioria das pessoas no Brasil faça sua parte no esforço conjunto para combater as mudanças climáticas` == '6' ~ 6,                                                                                                                                                                                                                                           
      `É provável que a maioria das pessoas no Brasil faça sua parte no esforço conjunto para combater as mudanças climáticas` == '7 (Concordo completamente)' ~ 7,                                                                                                                                                                                                                  
    ),
    MudancaClimatica8 =  case_when (	
      `É provável que os jovens no Brasil façam sua parte no esforço conjunto para combater as mudanças climáticas.` == '1 (Discordo completamente)' ~ 1,                                                                                                                                                                                                                            
      `É provável que os jovens no Brasil façam sua parte no esforço conjunto para combater as mudanças climáticas.` == '2' ~ 2,                                                                                                                                                                                                                                                     
      `É provável que os jovens no Brasil façam sua parte no esforço conjunto para combater as mudanças climáticas.` == '3' ~ 3,                                                                                                                                                                                                                                                     
      `É provável que os jovens no Brasil façam sua parte no esforço conjunto para combater as mudanças climáticas.` == '4' ~ 4,                                                                                                                                                                                                                                                     
      `É provável que os jovens no Brasil façam sua parte no esforço conjunto para combater as mudanças climáticas.` == '5' ~ 5,                                                                                                                                                                                                                                                     
      `É provável que os jovens no Brasil façam sua parte no esforço conjunto para combater as mudanças climáticas.` == '6' ~ 6,                                                                                                                                                                                                                                                     
      `É provável que os jovens no Brasil façam sua parte no esforço conjunto para combater as mudanças climáticas.` == '7 (Concordo completamente)' ~ 7,                                                                                                                                                                                                                            
    ),
    MudancaClimatica9 =  case_when (	
      `É provável que as pessoas mais velhas no Brasil façam sua parte no esforço conjunto para combater as mudanças climáticas.` == '1 (Discordo completamente)' ~ 1,                                                                                                                                                                                                               
      `É provável que as pessoas mais velhas no Brasil façam sua parte no esforço conjunto para combater as mudanças climáticas.` == '2' ~ 2,                                                                                                                                                                                                                                        
      `É provável que as pessoas mais velhas no Brasil façam sua parte no esforço conjunto para combater as mudanças climáticas.` == '3' ~ 3,                                                                                                                                                                                                                                        
      `É provável que as pessoas mais velhas no Brasil façam sua parte no esforço conjunto para combater as mudanças climáticas.` == '4' ~ 4,                                                                                                                                                                                                                                        
      `É provável que as pessoas mais velhas no Brasil façam sua parte no esforço conjunto para combater as mudanças climáticas.` == '5' ~ 5,                                                                                                                                                                                                                                        
      `É provável que as pessoas mais velhas no Brasil façam sua parte no esforço conjunto para combater as mudanças climáticas.` == '6' ~ 6,                                                                                                                                                                                                                                        
      `É provável que as pessoas mais velhas no Brasil façam sua parte no esforço conjunto para combater as mudanças climáticas.` == '7 (Concordo completamente)' ~ 7,
    ),
    MudancaClimatica10 = case_when (
      `Se as pessoas no Brasil fizerem a sua parte, juntas podem ajudar a combater as mudanças climáticas.` == '1 (Discordo completamente)' ~ 1,                                                                                                                                                                                                                                                                                                                                                                                                                                                             
      `Se as pessoas no Brasil fizerem a sua parte, juntas podem ajudar a combater as mudanças climáticas.` == '2' ~ 2,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
      `Se as pessoas no Brasil fizerem a sua parte, juntas podem ajudar a combater as mudanças climáticas.` == '3' ~ 3,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
      `Se as pessoas no Brasil fizerem a sua parte, juntas podem ajudar a combater as mudanças climáticas.` == '4' ~ 4,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
      `Se as pessoas no Brasil fizerem a sua parte, juntas podem ajudar a combater as mudanças climáticas.` == '5' ~ 5,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
      `Se as pessoas no Brasil fizerem a sua parte, juntas podem ajudar a combater as mudanças climáticas.` == '6' ~ 6,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
      `Se as pessoas no Brasil fizerem a sua parte, juntas podem ajudar a combater as mudanças climáticas.` == '7 (Concordo completamente)' ~ 7     
    ),
    MudancaClimatica11 = case_when (                                                                                                                                                                                                                                                                                                                                                                                                                                                        
      `Como jovem, há coisas que eu posso fazer na minha rotina diária para ajudar a combater as mudanças climáticas.` == '1 (Discordo completamente)' ~ 1,                                                                                                                                                                                                                                                                                                                                                                                                                                                  
      `Como jovem, há coisas que eu posso fazer na minha rotina diária para ajudar a combater as mudanças climáticas.` == '2' ~ 2,                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
      `Como jovem, há coisas que eu posso fazer na minha rotina diária para ajudar a combater as mudanças climáticas.` == '3' ~ 3,                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
      `Como jovem, há coisas que eu posso fazer na minha rotina diária para ajudar a combater as mudanças climáticas.` == '4' ~ 4,                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
      `Como jovem, há coisas que eu posso fazer na minha rotina diária para ajudar a combater as mudanças climáticas.` == '5' ~ 5,                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
      `Como jovem, há coisas que eu posso fazer na minha rotina diária para ajudar a combater as mudanças climáticas.` == '6' ~ 6,                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
      `Como jovem, há coisas que eu posso fazer na minha rotina diária para ajudar a combater as mudanças climáticas.` == '7 (Concordo completamente)' ~ 7   
    ),
    MudancaClimatica12 = case_when (                                                                                                                                                                                                                                                                                                                                                                                                                                              
      `Há coisas que pessoas mais velhas podem fazer na sua rotina diária para ajudar a combater as mudanças climáticas.` == '1 (Discordo completamente)' ~ 1,                                                                                                                                                                                                                                                                                                                                                                                                                                               
      `Há coisas que pessoas mais velhas podem fazer na sua rotina diária para ajudar a combater as mudanças climáticas.` == '2' ~ 2,                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
      `Há coisas que pessoas mais velhas podem fazer na sua rotina diária para ajudar a combater as mudanças climáticas.` == '3' ~ 3,                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
      `Há coisas que pessoas mais velhas podem fazer na sua rotina diária para ajudar a combater as mudanças climáticas.` == '4' ~ 4,                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
      `Há coisas que pessoas mais velhas podem fazer na sua rotina diária para ajudar a combater as mudanças climáticas.` == '5' ~ 5,                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
      `Há coisas que pessoas mais velhas podem fazer na sua rotina diária para ajudar a combater as mudanças climáticas.` == '6' ~ 6,                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
      `Há coisas que pessoas mais velhas podem fazer na sua rotina diária para ajudar a combater as mudanças climáticas.` == '7 (Concordo completamente)' ~ 7
    ),
    MudancaClimatica13 = case_when (                                                                                                                                                                                                                                                                                                                                                                                                                                              
      `Há coisas que o governo pode fazer para ajudar a combater as mudanças climáticas.` == '1 (Discordo completamente)' ~ 1,                                                                                                                                                                                                                                                                                                                                                     
      `Há coisas que o governo pode fazer para ajudar a combater as mudanças climáticas.` == '2' ~ 2,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
      `Há coisas que o governo pode fazer para ajudar a combater as mudanças climáticas.` == '3' ~ 3,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
      `Há coisas que o governo pode fazer para ajudar a combater as mudanças climáticas.` == '4' ~ 4,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
      `Há coisas que o governo pode fazer para ajudar a combater as mudanças climáticas.` == '5' ~ 5,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
      `Há coisas que o governo pode fazer para ajudar a combater as mudanças climáticas.` == '6' ~ 6,                                                                                                                                                                                                                                                                                                                                                                                              
      `Há coisas que o governo pode fazer para ajudar a combater as mudanças climáticas.` == '7 (Concordo completamente)' ~ 7  
    ),
    MudancaClimatica14 = case_when (                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
      `No mês passado, com que frequência você passou tempo nas áreas ao ar livre em sua região?` == 'Algumas vezes por mês' ~ 3,                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
      `No mês passado, com que frequência você passou tempo nas áreas ao ar livre em sua região?` == 'Algumas vezes por semana' ~ 4,                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
      `No mês passado, com que frequência você passou tempo nas áreas ao ar livre em sua região?` == 'Nunca' ~ 1,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
      `No mês passado, com que frequência você passou tempo nas áreas ao ar livre em sua região?` == 'Raramente' ~ 2,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
      `No mês passado, com que frequência você passou tempo nas áreas ao ar livre em sua região?` == 'Todos os dias' ~ 5 
    ),
    MudancaClimatica15 = case_when (                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
      `[Um estudo realizado em 2021]Mais cedo na pesquisa, você viu resultados de um estudo que foi publicado na Folha de São Paulo mostra que a maioria dos brasileiros (64%) com mais de 60 anos não acredita que cientistas e ambientalistas exageram ao tratar da crise do clima, isto é, pessoas mais velhas acreditam nos alertas de cientistas, demonstrando preocupação em relação às mudanças climáticas.Quão precisamente você acha que este resultado da pesquisa reflete o quão preocupadas as pessoas mais velhas no Brasil estão com as mudanças climáticas?` == '1 (Nada preciso)' ~ 1,       
      `[Um estudo realizado em 2021]Mais cedo na pesquisa, você viu resultados de um estudo que foi publicado na Folha de São Paulo mostra que a maioria dos brasileiros (64%) com mais de 60 anos não acredita que cientistas e ambientalistas exageram ao tratar da crise do clima, isto é, pessoas mais velhas acreditam nos alertas de cientistas, demonstrando preocupação em relação às mudanças climáticas.Quão precisamente você acha que este resultado da pesquisa reflete o quão preocupadas as pessoas mais velhas no Brasil estão com as mudanças climáticas?` == '2' ~ 2,                      
      `[Um estudo realizado em 2021]Mais cedo na pesquisa, você viu resultados de um estudo que foi publicado na Folha de São Paulo mostra que a maioria dos brasileiros (64%) com mais de 60 anos não acredita que cientistas e ambientalistas exageram ao tratar da crise do clima, isto é, pessoas mais velhas acreditam nos alertas de cientistas, demonstrando preocupação em relação às mudanças climáticas.Quão precisamente você acha que este resultado da pesquisa reflete o quão preocupadas as pessoas mais velhas no Brasil estão com as mudanças climáticas?` == '3' ~ 3,                      
      `[Um estudo realizado em 2021]Mais cedo na pesquisa, você viu resultados de um estudo que foi publicado na Folha de São Paulo mostra que a maioria dos brasileiros (64%) com mais de 60 anos não acredita que cientistas e ambientalistas exageram ao tratar da crise do clima, isto é, pessoas mais velhas acreditam nos alertas de cientistas, demonstrando preocupação em relação às mudanças climáticas.Quão precisamente você acha que este resultado da pesquisa reflete o quão preocupadas as pessoas mais velhas no Brasil estão com as mudanças climáticas?` == '4' ~ 4,                      
      `[Um estudo realizado em 2021]Mais cedo na pesquisa, você viu resultados de um estudo que foi publicado na Folha de São Paulo mostra que a maioria dos brasileiros (64%) com mais de 60 anos não acredita que cientistas e ambientalistas exageram ao tratar da crise do clima, isto é, pessoas mais velhas acreditam nos alertas de cientistas, demonstrando preocupação em relação às mudanças climáticas.Quão precisamente você acha que este resultado da pesquisa reflete o quão preocupadas as pessoas mais velhas no Brasil estão com as mudanças climáticas?` == '5' ~ 5,                      
      `[Um estudo realizado em 2021]Mais cedo na pesquisa, você viu resultados de um estudo que foi publicado na Folha de São Paulo mostra que a maioria dos brasileiros (64%) com mais de 60 anos não acredita que cientistas e ambientalistas exageram ao tratar da crise do clima, isto é, pessoas mais velhas acreditam nos alertas de cientistas, demonstrando preocupação em relação às mudanças climáticas.Quão precisamente você acha que este resultado da pesquisa reflete o quão preocupadas as pessoas mais velhas no Brasil estão com as mudanças climáticas?` == '6' ~ 6,                      
      `[Um estudo realizado em 2021]Mais cedo na pesquisa, você viu resultados de um estudo que foi publicado na Folha de São Paulo mostra que a maioria dos brasileiros (64%) com mais de 60 anos não acredita que cientistas e ambientalistas exageram ao tratar da crise do clima, isto é, pessoas mais velhas acreditam nos alertas de cientistas, demonstrando preocupação em relação às mudanças climáticas.Quão precisamente você acha que este resultado da pesquisa reflete o quão preocupadas as pessoas mais velhas no Brasil estão com as mudanças climáticas?` == '7 (Extremamente preciso)' ~ 7
    )
  )


  #Para cada ação, por favor escolha se você acha que ela tem um grande efeito, médio efeito ou pequeno efeito. Pense no impacto de cada ação ao longo de um período de um ano, a menos que seja indicado de outra forma.
  data <- data %>%
    mutate (
      Efeito1 = case_when (
        `Evitar um voo de longa distância (ou seja, 6 horas ou mais)` == 'Grande efeito' ~ 3,        
        `Evitar um voo de longa distância (ou seja, 6 horas ou mais)` == 'Médio efeito' ~ 2,         
        `Evitar um voo de longa distância (ou seja, 6 horas ou mais)` == 'Pequeno efeito' ~ 1
      ),
      Efeito2 = case_when (
        `Comprar coisas de maior durabilidade (ex.: roupas)` == 'Grande efeito' ~ 3,                 
        `Comprar coisas de maior durabilidade (ex.: roupas)` == 'Médio efeito' ~ 2,                  
        `Comprar coisas de maior durabilidade (ex.: roupas)` == 'Pequeno efeito' ~ 1                
      ),
      Efeito3 = case_when (
        `Comprar apenas alimentos locais` == 'Grande efeito' ~ 3,                                    
        `Comprar apenas alimentos locais` == 'Médio efeito' ~ 2,                                     
        `Comprar apenas alimentos locais` == 'Pequeno efeito' ~ 1                                   
      ),
      Efeito4 = case_when (
        `Comprar apenas alimentos orgânicos` == 'Grande efeito' ~ 3,                                 
        `Comprar apenas alimentos orgânicos` == 'Médio efeito' ~ 2,                                  
        `Comprar apenas alimentos orgânicos` == 'Pequeno efeito' ~ 1                                
      ),
      Efeito5 = case_when (
        `Comprar apenas alimentos sem embalagem` == 'Grande efeito' ~ 3,                             
        `Comprar apenas alimentos sem embalagem` == 'Médio efeito' ~ 2,                              
        `Comprar apenas alimentos sem embalagem` == 'Pequeno efeito' ~ 1                            
      ),
      Efeito6 = case_when (
        `Seguir uma dieta baseada em plantas (vegana)` == 'Grande efeito' ~ 3,                       
        `Seguir uma dieta baseada em plantas (vegana)` == 'Médio efeito' ~ 2,                        
        `Seguir uma dieta baseada em plantas (vegana)` == 'Pequeno efeito' ~ 1                      
      ),
      Efeito7 = case_when (
        `Secar roupas apenas no varal` == 'Grande efeito' ~ 3,                                       
        `Secar roupas apenas no varal` == 'Médio efeito' ~ 2,                                        
        `Secar roupas apenas no varal` == 'Pequeno efeito' ~ 1                                      
      ),
      Efeito8 = case_when (
        `Minimizar o desperdício de alimentos` == 'Grande efeito' ~ 3,                               
        `Minimizar o desperdício de alimentos` == 'Médio efeito' ~ 2,                                
        `Minimizar o desperdício de alimentos` == 'Pequeno efeito' ~ 1                              
      ),
      Efeito9 = case_when (
        `Não jogar lixo no chão` == 'Grande efeito' ~ 3,                                             
        `Não jogar lixo no chão` == 'Médio efeito' ~ 2,                                              
        `Não jogar lixo no chão` == 'Pequeno efeito' ~ 1                                            
      ),
      Efeito10 = case_when (
        `Reciclar o máximo possível` == 'Grande efeito' ~ 3,                                         
        `Reciclar o máximo possível` == 'Médio efeito' ~ 2,                                          
        `Reciclar o máximo possível` == 'Pequeno efeito' ~ 1                                        
      ),
      Efeito11 = case_when (
        `Reutilizar coisas antigas em vez de comprar novas` == 'Grande efeito' ~ 3,                  
        `Reutilizar coisas antigas em vez de comprar novas` == 'Médio efeito' ~ 2,                   
        `Reutilizar coisas antigas em vez de comprar novas` == 'Pequeno efeito' ~ 1                 
      ),
      Efeito12 = case_when (
        `Usar transporte público, bicicleta ou caminhar em vez de usar carro` == 'Grande efeito' ~ 3,
        `Usar transporte público, bicicleta ou caminhar em vez de usar carro` == 'Médio efeito' ~ 2, 
        `Usar transporte público, bicicleta ou caminhar em vez de usar carro` == 'Pequeno efeito' ~ 3
      ),
      Efeito13 = case_when (
        `Usar sacolas reutilizáveis para compras` == 'Grande efeito' ~ 3,                            
        `Usar sacolas reutilizáveis para compras` == 'Médio efeito' ~ 2,                             
        `Usar sacolas reutilizáveis para compras` == 'Pequeno efeito' ~ 1 
      )
    )